/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_maximum_fastride_fastcv_FastCVWrapper */

#ifndef _Included_com_maximum_fastride_fastcv_FastCVWrapper
#define _Included_com_maximum_fastride_fastcv_FastCVWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_maximum_fastride_fastcv_FastCVWrapper
 * Method:    FrameTick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_maximum_fastride_fastcv_FastCVWrapper_FrameTick
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
